import type { Service } from "./types";

export const seedServices: Service[] = [
  {
    id: "serv-1",
    name: "Afilado estándar de guillotina",
    description: "Rectificado de filo en esmeril plano, asentado a mano",
    basePrice: 950,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-1",
  },
  {
    id: "serv-2",
    name: "Rectificado completo de guillotina",
    description: "Rectificado de cuerpo y filo, incluye despuntes profundos",
    basePrice: 1850,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-1",
  },
  {
    id: "serv-3",
    name: "Afilado de disco rebanador",
    description: "Vaciado y asentado de disco, balanceo incluido",
    basePrice: 380,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-2",
  },
  {
    id: "serv-4",
    name: "Afilado de disco con rectificado de plato",
    description: "Para discos con alabeo o desgaste irregular",
    basePrice: 620,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-2",
  },
  {
    id: "serv-5",
    name: "Afilado de cruceta y cedazo",
    description: "Esmerilado plano de juego completo de molino",
    basePrice: 290,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-3",
  },
  {
    id: "serv-6",
    name: "Soldado y afilado de sierra cinta",
    description: "Unión a tope, recocido y afilado de banda",
    basePrice: 450,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-4",
  },
  {
    id: "serv-7",
    name: "Afilado de sierra cinta",
    description: "Afilado y triscado de dentado",
    basePrice: 320,
    active: true,
    createdAt: "2025-11-03T09:00:00.000Z",
    bladeTypeId: "blade-4",
  },
  {
    id: "serv-8",
    name: "Afilado de rotor granulador",
    description: "Rectificado de juego de cuchillas rotativas y fijas",
    basePrice: 2400,
    active: true,
    createdAt: "2026-01-12T09:00:00.000Z",
    bladeTypeId: "blade-5",
  },
  {
    id: "serv-9",
    name: "Ajuste de claros de granulador",
    description: "Calibración de claro cuchilla-contracuchilla en sitio",
    basePrice: 1200,
    active: false,
    createdAt: "2026-01-12T09:00:00.000Z",
    bladeTypeId: "blade-5",
  },
  {
    id: "serv-10",
    name: "Afilado de cuchilla textil",
    description: "Afilado de cuchilla vertical u octogonal",
    basePrice: 260,
    active: true,
    createdAt: "2026-02-02T09:00:00.000Z",
    bladeTypeId: "blade-6",
  },
];
